### ISSUE TITLE
Setting the model appears to break the render

### ISSUE THREAD

**Issue by staxmanade** [balthazar/ng-markdown#21]
Given the following plnkr: http://plnkr.co/edit/fVBlVyb1fRwfwh0zAKzY?p=preview

This is basically setting the model value on a timeout.

I notice the following error in the console:

```
 TypeError: Cannot read property 'appendChild' of undefined
    at makeSpritedButtonRow (https://rawgit.com/Apercu/ng-markdown/master/dist/ng-markdown.js:2914:34)
    at new UIManager (https://rawgit.com/Apercu/ng-markdown/master/dist/ng-markdown.js:2696:9)
    at run (https://rawgit.com/Apercu/ng-markdown/master/dist/ng-markdown.js:1656:25)
    at post (https://rawgit.com/Apercu/ng-markdown/master/dist/ng-markdown.js:105:22)
    at https://code.angularjs.org/1.2.25/angular.js:7113:44
    at nodeLinkFn (https://code.angularjs.org/1.2.25/angular.js:6711:13)
    at compositeLinkFn (https://code.angularjs.org/1.2.25/angular.js:6105:13)
    at nodeLinkFn (https://code.angularjs.org/1.2.25/angular.js:6705:24)
    at compositeLinkFn (https://code.angularjs.org/1.2.25/angular.js:6105:13)
    at compositeLinkFn (https://code.angularjs.org/1.2.25/angular.js:6108:13) <textarea ng-keydown="refresh()" ng-model="sampleMarkdown" class="ng-isolate-scope ng-pristine ng-valid ng-scope wmd-input" msd-elastic="" style="overflow: hidden; word-wrap: break-word; resize: horizontal;">
```

Thoughts?

**Comment by balthazar** [comment]
Hum, I think there is two errors here: first, you have not created a button bar, and that's why you have this error. I'll make it non-mandatory soon. The second problem is when setting the value of the model, the recalculation of the height is not done, you can try to input something and you will see the resize, will work on it too.

Thanks for the feedback!

**Comment by staxmanade** [comment]
Ok - you're right... I put the button bar and preview in this sample.

http://plnkr.co/edit/cXTatxu4MuffdqSnNd4d?p=preview

What I'm having an issue with is that the preview never gets rendered (until I execute a keydown/up in side of the txt box).

Would like the preview to render when the model gets set.

**Comment by balthazar** [comment]
Yeah I get that, I've already corrected the error when you've not set a bar, will investigate on how to fix your main problem

**Comment by staxmanade** [comment]
:+1: thanks for taking a look!!!
